### ISSUE TITLE
[Question]: Status/Roadmap of this project

### ISSUE THREAD

**Issue by atifaziz** [linezero/HtmlAgilityPack#1]
Question here is same as posted to zulfahmi93/HtmlAgilityPack.NetCore#4 and noliar/HtmlAgilityPack.NetCore#1. I'm cross-referencing in the hope to get a dialogue going around whether or not it makes sense to the respective owners to get a consolidated effort going forward (agendas & goals permitting).

**Comment by linezero** [comment]
Hi,

**Comment by atifaziz** [comment]
@linezero [said](https://github.com/zulfahmi93/HtmlAgilityPack.NetCore/issues/4#issuecomment-240605516):

> Hi,I am want need use it,but before no know this.Source from codeplex ,I just migrate to .NET Core.

Moving this discussion to noliar/HtmlAgilityPack.NetCore#1.
